# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{slim}
  s.version = "0.4.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Andrew Stone"]
  s.date = %q{2010-10-03}
  s.description = %q{Slim is a template language whose goal is reduce the syntax to the essential parts without becoming cryptic.}
  s.email = %q{andy@stonean.com}
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    ".gitignore",
     "README.md",
     "Rakefile",
     "lib/slim.rb",
     "lib/slim/compiler.rb",
     "lib/slim/engine.rb",
     "lib/slim/optimizer.rb",
     "lib/slim/rails.rb",
     "slim.gemspec",
     "test/helper.rb",
     "test/slim/test_compiler.rb",
     "test/slim/test_engine.rb",
     "test/test_slim.rb",
     "vim/slim.vim",
     "vim/test.slim"
  ]
  s.homepage = %q{http://github.com/stonean/slim}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{slim}
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Slim is a template language.}
  s.test_files = [
    "test/helper.rb",
     "test/test_slim.rb",
     "test/slim/test_engine.rb",
     "test/slim/test_compiler.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

